// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4W6mK3YdCXt2oiSkpKtir9yqMVqGfsAI',
    appId: '1:546161464868:web:ab17e954e5452a8d8aaab1',
    messagingSenderId: '546161464868',
    projectId: 'applyyc-e658b',
    authDomain: 'applyyc-e658b.firebaseapp.com',
    storageBucket: 'applyyc-e658b.appspot.com',
    measurementId: 'G-N5GK8N0R5C',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY3hkvfvrVx70cyQv7-KoxeXI75jjwfWc',
    appId: '1:546161464868:ios:5a0517263328b6d58aaab1',
    messagingSenderId: '546161464868',
    projectId: 'applyyc-e658b',
    storageBucket: 'applyyc-e658b.appspot.com',
    iosClientId: '546161464868-mu4nobh7ce7hpmp3umbn2n706f00j62a.apps.googleusercontent.com',
    iosBundleId: 'com.example.applyyc',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZG3cxmPJfA4Xib3jI5APUKa_yKqLTwt8',
    appId: '1:546161464868:android:d657a7fbeeb6cd628aaab1',
    messagingSenderId: '546161464868',
    projectId: 'applyyc-e658b',
    storageBucket: 'applyyc-e658b.appspot.com',
  );

}